# Generated by Django 3.0.7 on 2020-06-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyowners', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='propertyOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='propertyowners.PropertyOwner'),
        ),
    ]
